// bridge-extension.ts (T02, corrected): thin Pi extension for the
// Telegram bridge.
//
// Register with: pi --mode rpc -e extension/bridge-extension.ts
//
// Scope (documented honestly — this is a policy gate, NOT an OS sandbox):
// - tool_call gate: read allowed; write/edit confirmed by the human with
//   a fingerprint and a dated backup; shell/MCP/subagents/network and
//   unknown tools are denied. No command strings ever come from chat.
// - bridge_decision is a REAL awaited question tool: pi emits
//   tool_execution_start, the awaited ctx.ui.select surfaces as an
//   extension_ui_request dialog, and tool_execution_end completes the
//   host request correlated by toolCallId (never a model-provided id).
// - /bridge-demo command: awaited ui.select demo of the remote approval
//   flow. The host generates a single-use nonce passed as the command
//   argument; the follow-up notify is a strict JSON {nonce, choice}
//   object that only completes a matching lifecycle (H3).

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { copyFileSync, existsSync } from "node:fs";
import {
  actionFingerprint,
  checkWorkspacePath,
  classifyTool,
  planBackupPath,
} from "../src/policy.mjs";

export const BRIDGE_DECISION_TOOL = "bridge_decision";

interface WriteEditInput {
  path?: string;
  [key: string]: unknown;
}

export default function bridgeExtension(pi: ExtensionAPI) {
  // --- Policy gate on every tool call ---------------------------------
  pi.on("tool_call", async (event, ctx) => {
    const verdict = classifyTool(event.toolName);
    if (verdict.verdict === "allow") {
      return;
    }
    if (verdict.verdict === "deny") {
      return { block: true, reason: `bridge policy: ${verdict.reason}` };
    }

    // confirm: write/edit. Path guard first (fail closed), then a dated
    // backup of the existing file, then the human confirmation.
    const input = (event.input ?? {}) as WriteEditInput;
    const pathCheck = checkWorkspacePath({
      workspaceRoot: ctx.cwd,
      requestedPath: typeof input.path === "string" ? input.path : "",
    });
    if (pathCheck.verdict === "deny") {
      return { block: true, reason: `bridge policy: ${pathCheck.reason}` };
    }

    const fingerprint = actionFingerprint({ tool: event.toolName, args: input });
    let backupNote = "new file (no backup needed)";
    if (existsSync(pathCheck.resolved!)) {
      const backup = planBackupPath({
        targetPath: pathCheck.resolved!,
        now: Date.now(),
      });
      if (backup.verdict !== "ok") {
        return { block: true, reason: `bridge policy: ${backup.reason}` };
      }
      try {
        copyFileSync(pathCheck.resolved!, backup.backupPath);
        backupNote = `backup: ${backup.backupPath}`;
      } catch {
        return {
          block: true,
          reason: "bridge policy: could not create the dated backup; write blocked",
        };
      }
    }

    const ok = await ctx.ui.confirm(
      "Approve remote write?",
      `${event.toolName}: ${input.path}\nfingerprint: ${fingerprint}\n${backupNote}`,
    );
    if (!ok) {
      return { block: true, reason: "Blocked by human (bridge)" };
    }
  });

  // --- Awaited question tool (B4) ---------------------------------------
  // The agent calls this to ask the remote human a question. pi emits
  // tool_execution_start before execution; the awaited select surfaces as
  // a dialog the bridge host persists; tool_execution_end then carries the
  // REAL outcome correlated by toolCallId. No requestId from the model.
  pi.registerTool({
    name: BRIDGE_DECISION_TOOL,
    label: "Ask the bridge user",
    description:
      "Ask the remote human (Telegram bridge) a question and return their answer. " +
      "Use when a decision must be confirmed by the human before continuing.",
    parameters: Type.Object({
      question: Type.String({ description: "The question shown to the human" }),
      choices: Type.Array(Type.String(), {
        minItems: 1,
        maxItems: 8,
        description: "The options the human can pick from",
      }),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const answer = await ctx.ui.select(params.question, params.choices);
      const text =
        answer === undefined
          ? "no answer (dialog timed out or was cancelled)"
          : `the human answered: ${answer}`;
      return {
        content: [{ type: "text", text }],
        details: { choice: answer ?? null },
      };
    },
  });

  // --- /bridge-demo (H3) -------------------------------------------------
  // args = the single-use nonce generated by the bridge host when it
  // locally initiated the demo lifecycle. The follow-up notify is a strict
  // JSON {nonce, choice} object; the host completes the demo request only
  // on an exact nonce match. Arbitrary text never completes anything.
  pi.registerCommand("bridge-demo", {
    description: "Remote approval demo: shows how a Telegram decision reaches pi",
    handler: async (args, ctx) => {
      const nonce = typeof args === "string" ? args.trim() : "";
      const choice = await ctx.ui.select("Bridge demo: pick an option", [
        "Option A",
        "Option B",
      ]);
      // The awaited resolution means pi applied the response. The notify
      // below is the host-visible demo signal (commands cannot run tools).
      ctx.ui.notify(JSON.stringify({ nonce, choice }), "info");
    },
  });
}
